### ISSUE TITLE
Markdown Button Missing after Upgrade to WP 4.4

### ISSUE THREAD

**Issue by salcode** [markjaquith/markdown-on-save#13]
After updating to WordPress 4.4, the "M" button on the <strong>Publish</strong> box is no longer there.  Posts that already existed and were using Markdown continued to use it but there is no longer a way to set new posts to use Markdown.

## Pre-4.4
![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f31313939382f3135333930382f30643865626437302d373630392d313165322d396632372d3235613838646466363938622e6a7067](https://cloud.githubusercontent.com/assets/5194588/11907220/25aa3244-a5a0-11e5-854b-e2928bd2f7f6.jpeg)

## 4.4
![screenshot 2015-12-18 15 58 44](https://cloud.githubusercontent.com/assets/5194588/11907235/3aa6b2d0-a5a0-11e5-988e-cd561cf0dc14.png)

**Comment by rich8** [comment]
Thanks to Will Norris for this fix - much appreciated
